"use strict";

// Canonical debug event types and categories
// Scaffolding only. No runtime wiring.

const DEBUG_EVENT_CATEGORIES = Object.freeze({
  SESSION: "session",
  TRANSPORT: "transport",
  PROVIDER: "provider",
  TRANSCRIPT: "transcript",
  CONVERSATION: "conversation",
  SNAPSHOT: "snapshot",
  INTERRUPT: "interrupt",
  FINALIZATION: "finalization",
  WEBHOOK: "webhook",
  MEMORY: "memory",
  RECORDING: "recording",
  ERROR: "error",
});

const DEBUG_EVENT_TYPES = Object.freeze({
  CALL_SESSION_CREATED: "CALL_SESSION_CREATED",
  CALL_SESSION_STATE_CHANGED: "CALL_SESSION_STATE_CHANGED",
  CALL_SESSION_ATTACHED_TWILIO_WS: "CALL_SESSION_ATTACHED_TWILIO_WS",
  CALL_SESSION_ATTACHED_PROVIDER: "CALL_SESSION_ATTACHED_PROVIDER",

  TWILIO_STREAM_STARTED: "TWILIO_STREAM_STARTED",
  TWILIO_STREAM_STOPPED: "TWILIO_STREAM_STOPPED",
  TWILIO_MARK_RECEIVED: "TWILIO_MARK_RECEIVED",
  TWILIO_MEDIA_SENT: "TWILIO_MEDIA_SENT",
  TWILIO_WS_CLOSED: "TWILIO_WS_CLOSED",
  TWILIO_WS_ERROR: "TWILIO_WS_ERROR",

  PROVIDER_CONNECTED: "PROVIDER_CONNECTED",
  PROVIDER_SETUP_SENT: "PROVIDER_SETUP_SENT",
  PROVIDER_CLOSED: "PROVIDER_CLOSED",
  PROVIDER_ERROR: "PROVIDER_ERROR",

  TRANSCRIPT_CHUNK_BUFFERED: "TRANSCRIPT_CHUNK_BUFFERED",
  TRANSCRIPT_FLUSH_SCHEDULED: "TRANSCRIPT_FLUSH_SCHEDULED",
  TRANSCRIPT_FLUSHED: "TRANSCRIPT_FLUSHED",
  TRANSCRIPT_SUPPRESSED: "TRANSCRIPT_SUPPRESSED",

  CALLER_NAME_CAPTURED: "CALLER_NAME_CAPTURED",
  CALLBACK_CONFIRMED: "CALLBACK_CONFIRMED",
  IMMEDIATE_TEXT_SENT: "IMMEDIATE_TEXT_SENT",
  CLOSING_DETECTED: "CLOSING_DETECTED",
  CLOSING_HANGUP_SCHEDULED: "CLOSING_HANGUP_SCHEDULED",

  SNAPSHOT_UPDATED: "SNAPSHOT_UPDATED",
  SNAPSHOT_CHECKPOINT_CREATED: "SNAPSHOT_CHECKPOINT_CREATED",

  BARGE_IN_TRIGGERED: "BARGE_IN_TRIGGERED",
  MODEL_INTERRUPTED: "MODEL_INTERRUPTED",
  ASSISTANT_PLAYBACK_STARTED: "ASSISTANT_PLAYBACK_STARTED",
  ASSISTANT_PLAYBACK_STOPPED: "ASSISTANT_PLAYBACK_STOPPED",

  FINALIZATION_REQUESTED: "FINALIZATION_REQUESTED",
  FINALIZATION_LOCK_ACQUIRED: "FINALIZATION_LOCK_ACQUIRED",
  FINALIZATION_DUPLICATE_IGNORED: "FINALIZATION_DUPLICATE_IGNORED",
  FINALIZATION_WINNER_SELECTED: "FINALIZATION_WINNER_SELECTED",
  FINALIZATION_SNAPSHOT_ONLY_APPLIED: "FINALIZATION_SNAPSHOT_ONLY_APPLIED",
  FINALIZATION_COMPLETED: "FINALIZATION_COMPLETED",
  FINALIZATION_FAILED: "FINALIZATION_FAILED",

  WEBHOOK_DISPATCH_ATTEMPT: "WEBHOOK_DISPATCH_ATTEMPT",
  WEBHOOK_DISPATCH_SUCCEEDED: "WEBHOOK_DISPATCH_SUCCEEDED",
  WEBHOOK_DISPATCH_FAILED: "WEBHOOK_DISPATCH_FAILED",
});

const SNAPSHOT_CHECKPOINT_LABELS = Object.freeze({
  CALL_START: "call_start",
  AFTER_CALLER_PROFILE: "after_caller_profile",
  AFTER_NAME_CAPTURE: "after_name_capture",
  AFTER_CALLBACK_CAPTURE: "after_callback_capture",
  AFTER_TRANSCRIPT_FLUSH_USER: "after_transcript_flush_user",
  AFTER_TRANSCRIPT_FLUSH_BOT: "after_transcript_flush_bot",
  BEFORE_FINALIZATION: "before_finalization",
  AFTER_FINALIZATION: "after_finalization",
  AFTER_BLOCKED_CALLER_MATCH: "after_blocked_caller_match",
  AFTER_PROVIDER_CLOSE: "after_provider_close",
});

module.exports = {
  DEBUG_EVENT_CATEGORIES,
  DEBUG_EVENT_TYPES,
  SNAPSHOT_CHECKPOINT_LABELS,
};
