"use strict";

const SSOT_FALLBACK_DEFAULTS = {
  BUSINESS_NAME: 'טופ קומרס',
  BOT_NAME: 'לילך',
  DEFAULT_LANGUAGE: 'he',
  MAIN_PHONE: 'אפס שלוש, תשע חמש חמש אחת ארבע ארבע ארבע',
  BUSINESS_EMAIL: '[email protected]',
  BUSINESS_ADDRESS: 'המלאכה 23 פארק אפק ראש העין',
  WORKING_HOURS: 'ימים א׳ עד ה׳ בין השעות תשע בבוקר עד חמש אחר הצהריים',
  BUSINESS_WEBSITE_URL: 'https://topcommerce.co.il/',
  VOICE_NAME: 'Callirrhoe',
  OPENING_SCRIPT: '{GREETING}, לילך מטופ קומרס. לקוחות חדשים או קיימים?',
  OPENING_SCRIPT_RETURNING: '{GREETING} {display_name}, לילך מטופ קומרס. במה אפשר לעזור?',
  NO_DATA_MESSAGE: 'אין לי את המידע המדויק כרגע, אבל אשמח לרשום את הפנייה כדי שנציג מטופ קומרס יחזור אליכם.',
  SUBJECT_MIN_WORDS: '1',
  CALLBACK_ASK_PHRASE: 'בסדר גמור. תרצו שנחזור למספר הזה או למספר אחר?',
  CALLBACK_RETRY_PHRASE: 'סליחה, לא שמעתי טוב, אנא חיזרו על המספר באופן רציף או ללא עצירה.',
  CALLBACK_CONFIRM_NEW_NUMBER_TEMPLATE: 'רק לוודא, המספר הוא {DIGITS_SPOKEN}. זה נכון?',
  CLOSING_sales: 'תודה רבה, רשמתי את הפרטים. נציג מכירות של טופ קומרס יחזור אליכם בהקדם. להתראות.',
  CLOSING_support: 'תודה רבה, רשמתי את הפרטים. נציג שירות של טופ קומרס יחזור אליכם בהקדם. להתראות.',
  CLOSING_callback: 'תודה רבה, רשמתי את הפרטים. מיד אשלח לכם הודעה לוואטסאפ עם סיכום השיחה, וגם שנציג או נציגה שלנו יחזרו אליכם בהקדם. להתראות.',
  CLOSING_info: 'תודה רבה. אם תרצו, אפשר גם להשאיר פנייה ונציג מטופ קומרס יחזור אליכם בהקדם. להתראות.',
  CLOSING_other: 'תודה רבה, רשמתי את הפרטים ואעביר את הפנייה לנציג מטופ קומרס. להתראות.',
  CLOSING_ASK_MORE: 'יש משהו נוסף שתרצו להוסיף לפני שאני מסיימת?',
  CLOSING_GOODBYE: 'תודה רבה, רשמתי את הפרטים. מיד אשלח לכם הודעה לוואטסאפ עם סיכום השיחה, וגם שנציג או נציגה שלנו יחזרו אליכם בהקדם. להתראות.',
  UNSUPPORTED_LANGUAGE_MESSAGE: 'מצטערת, כרגע אני מדברת בעברית. אם תרצו, אפשר להשאיר פרטים ונציג יחזור אליכם.',
  CALLBACK_WITHHELD_MESSAGE: 'שימו לב שהמספר שממנו התקשרתם חסוי, לכן אצטרך מספר טלפון לחזרה.',
  LEAD_MODE: 'intent_based',
  BUSINESS_DESCRIPTION: 'טופ קומרס מתמחה בריהוט משרדי, ציוד ארגונומי, כיסאות ארגונומיים, שולחנות מתכווננים, זרועות ומעמדי מסך, עכברים ומקלדות ארגונומיים ופתרונות ישיבה ועמידה למשרד, לבית ולמוסדות.',
  BUSINESS_OWNER: "",
  BUSINESS_EXPERIENCE_YEARS: "",
  BUSINESS_EXPERTISE: 'יבוא ויצוא של ציוד ארגונומי למשרד ולבית, ייעוץ והכוונה לבחירת פתרונות ארגונומיים, והתאמת מוצרים ללקוחות פרטיים, עסקים ומוסדות.',
  BUSINESS_AUTHORITIES_REPRESENTATION: "",
  BUSINESS_SPECIAL_NOTES: 'בחלק מהמוצרים ניתן להזמין מידות מותאמות אישית; במוצרים רבים באתר מצוינת גם פריסה נוחה של עד 6 תשלומים; קיימים גם פתרונות לארגונומיה לילדים ולמוסדות חינוך.',
  BUSINESS_SERVICES_LIST: 'כיסאות ארגונומיים, שולחנות חשמליים וידניים מתכווננים, שולחנות וארונות משרד, עמדות עמידה-ישיבה, זרועות ומעמדי מסך, עזרים ארגונומיים, עכברים ומקלדות, הדומים מתכווננים, פתרונות ארגונומיה לילדים ולמוסדות חינוך.',
  BLOCKED_CALLERS: "",
  CALL_LOG_WEBHOOK_URL: '',
  FINAL_WEBHOOK_URL: '',
  ABANDONED_WEBHOOK_URL: '',
  SUPABASE_USAGE_WEBHOOK_URL: "",
  WHATSAPP_SUMMARY_WEBHOOK_URL: '',
  CALL_LOG_AT_START: 'false',
  CALL_LOG_AT_END: 'true',
  CALL_LOG_MODE: 'end',
  FINAL_ON_STOP: 'false',
  FORCE_HANGUP_AFTER_CLOSE: 'true',
  HANGUP_AFTER_CLOSE_GRACE_MS: '10000',
  GEMINI_AUDIO_IN_FORMAT: 'ulaw8k',
  GEMINI_AUDIO_OUT_FORMAT: 'ulaw8k',
  VOICE_NAME_OVERRIDE: 'Callirrhoe',
  MB_VAD_THRESHOLD: '0.60',
  MB_VAD_SILENCE_MS: '320',
  MB_VAD_PREFIX_MS: '100',
  MB_AEC_ENABLED: 'true',
  MB_AEC_HISTORY_MS: '900',
  MB_AEC_SEARCH_MS: '180',
  MB_AEC_STRENGTH: '0.78',
  MB_AEC_CORR_THRESHOLD: '0.78',
  MB_AEC_DUCK_THRESHOLD: '0.62',
  MB_AEC_NEAR_SPEECH_FLOOR: '0.016',
  MB_AEC_ECHO_FLOOR: '0.01',
  MB_INTERRUPT_RECOVERY_ENABLED: 'true',
  MB_INTERRUPT_RECOVERY_WINDOW_MS: '2500',
  MB_AUDIO_NOISE_GATE_FLOOR: '320',

  MB_AUDIO_AGC_TARGET_RMS: '0.14',
  MB_AUDIO_AGC_MAX_GAIN: '4',
  MB_AUDIO_HIGHPASS_ALPHA: '0.97',
  MB_BARGE_IN_RMS_THRESHOLD: '0.028',
  MB_BARGE_IN_MIN_FRAMES: '4',
  MB_BARGEIN_ENABLED: 'true',
  MB_BARGEIN_MIN_MS: '220',
  MB_BARGEIN_COOLDOWN_MS: '650',
  MB_BARGEIN_AUDIO_DROP_MS: '35',
  MB_ENABLE_RECORDING: 'true',
  RECORDING_PROXY_TIMEOUT_MS: '20000',
  SILENCE_T1_MS: '13000',
  SILENCE_T2_MS: '15000',
  SILENCE_T3_MS: '22000',
  SILENCE_PROMPT_1: 'רק לבדוק שאתה עדיין איתי, במה אוכל לעזור?',
  SILENCE_PROMPT_2: 'אם תרצה שאעזור, ספר לי בקצרה מה הפנייה.',
  SILENCE_PROMPT_3: 'אם אין מענה, אוכל לסיים את השיחה או שנוכל לתאם חזרה. מה עדיף?',
  LEAD_PARSER_ENABLED: 'true',
  LEAD_PARSER_MODE: 'postcall',
  LEAD_PARSER_MODEL: 'gemini-2.0-flash',
  LEAD_SUMMARY_STYLE: 'crm_short',
  MB_ACK_NAME_TEMPLATE: 'תודה {NAME}, איך אפשר לעזור?',
  MB_DEFAULT_LANGUAGE: 'he',
  MB_LANGUAGE_SWITCH_MIN_CONSECUTIVE_UTTERANCES: '4',
  MB_LANGUAGE_LOCK_ENABLED: 'true',
  MB_USER_UTTERANCE_FLUSH_MS: '260',
  MB_BOT_UTTERANCE_FLUSH_MS: '900',
  MB_MIN_STABLE_UTTERANCE_CHARS: '4',
  MB_NUMERIC_CONTINUATION_GRACE_MS: '1100',
  MB_LOW_LATENCY_MODE: 'true',
  MB_NAME_MAX_ATTEMPTS: '2',
  MB_REQUIRE_NAME_BEFORE_DETAILS: 'true',
  MB_LOG_TRANSCRIPTS: 'true',
  MB_LOG_TURNS: 'false',
  MB_LOG_TURNS_MAX_CHARS: '900',
  MB_LOG_ASSISTANT_TEXT: 'false',
  MB_DEBUG: 'false',
  PROVIDER_MODE: 'gemini',
  GEMINI_LIVE_MODEL: 'gemini-2.5-flash-native-audio-preview-12-2025',
  GEMINI_LOCATION: 'us-central1',
  PUBLIC_BASE_URL: 'https://topcommerce.onrender.com',
  SSOT_TTL_MS: '60000',
  TIME_ZONE: 'Asia/Jerusalem',
  FINAL_RULE_MODE: 'twilio_completed_name_phone',
  ABANDONED_RULE_MODE: 'ended_before_complete',
  MIN_CALL_DURATION_FOR_FINAL: '0',
  MIN_UTTERANCES_FOR_FINAL: '0',
  WHATSAPP_SUMMARY_WEBHOOK_ENABLED: 'false',
  CALL_LOG_WEBHOOK_ENABLED: 'false',
  COMPLETE_WEBHOOK_ENABLED: 'false',
  ABANDONED_WEBHOOK_ENABLED: 'false',
  WEBHOOK_TIMEOUT_MS: '10000',
  WEBHOOK_RETRY_COUNT: '1',
  CALLBACK_ALT_NUMBER_PHRASE: 'אין בעיה, לאיזה מספר תרצו שנחזור?',
  REPORTS_ASK_TYPE_PHRASE: "",
  REPORTS_ASK_PERIOD_PHRASE: "",
  REPORTS_ASK_FORWHOM_PHRASE: "",
  MB_OPENING_PHASE_MAX_MS: '12000',
  MB_USER_TRANSCRIPT_FLUSH_MS: '420',
  MB_USER_TRANSCRIPT_STABLE_GAP_MS: '360',
  MB_USER_TRANSCRIPT_MIN_CHARS: '3',
  MB_USER_TRANSCRIPT_MIN_WORDS: '1',
  MB_USER_TRANSCRIPT_MAX_BUFFER_MS: '1600',
  MB_BOT_TRANSCRIPT_FLUSH_MS: '280',
  MB_BOT_TRANSCRIPT_STABLE_GAP_MS: '220',
  MB_END_CALL_DELAY_MS: '5000',
  LONG_SILENCE_HANGUP_ENABLED: 'true',
  LONG_SILENCE_HANGUP_MS: '120000',
};

module.exports = { SSOT_FALLBACK_DEFAULTS };
